common: &common
  adapter: postgresql
  username: autocomplete_demo
  password:
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: autocomplete_demo_development

test:
  <<: *common
  database: autocomplete_demo_test

production:
  <<: *common
  database: autocomplete_demo_production
